[nfs]
172.31.44.233 ansible_ssh_user=ec2-user

[webservers]
172.31.43.169 ansible_ssh_user=ec2-user
172.31.38.41 ansible_ssh_user=ec2-user

[db]
172.31.33.130 ansible_ssh_user=ec2-user 

[lb]
172.31.82.72 ansible_ssh_user=ubuntu
