---
- name: update webservers, nfs and db 
  hosts: webservers, nfs, db
  become: yes
  tasks:
    - name: ensure wireshark is at the latest version
      yum:
        name: wireshark
        state: latest
   

- name: update lb 
  hosts: lb
  become: yes
  tasks:
    - name: ensure wireshark is at the latest version
      apt: 
        name: wireshark
        state: latest

    - 

